# Generated by Django 5.2.1 on 2026-08-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=120)),
                ('titular', models.CharField(blank=True, help_text="Titular o entidad (opcional), ej: 'Fernanda Abraham' o 'EasyPrint'.", max_length=120)),
                ('activo', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alias de pago',
                'verbose_name_plural': 'Alias de pago',
                'ordering': ('-activo', 'alias'),
            },
        ),
    ]
