# Generated by Django 5.2.1 on 2026-08-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aliaspago'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclaimer', models.TextField(blank=True, default='-El presente presupuesto puede variar sin previo aviso ya que todos nuestros insumos estan dolarizados.\n-El pedido se considera efectivo y por lo tanto se comenzará a trabajar en el mismo, una vez recibida la seña del 50% del valor pactado. Se factura finalizado y pagado todo el trabajo. El siguiente presupuesto es SIN IVA. Contamos con Factura C solamente.\n- Aún en trabajos señados si la demora del mismo es generada por el cliente (no responde mensajes, no aprueba diseños, no manda correcciones, no retira en un lapso de 2 dias despues de informado que su pedido esta listo) se puede actualizar el valor del pedido.\n-Salvo casos en donde se aclare lo contrario el trabajo será entregado/estará disponible para ser retirado en 15 dias hábiles desde recibida la seña. En caso de querer retirarlo se recomienda y se agradece la previa coordinación por alguno de nuestros canales de comunicación. En pedidos mayoristas pactar fecha de entrega con el vendedor.\n-Los trabajos con caracter de urgente se reciben a discreción de EasyPrint quien dispondrá de la opción de incrementar hasta un 30% el valor del pedido y el mismo será entregado en menos de 24hs hábiles. De no poder cumplir esto último el cliente tendrá la opción de cancelar el pedido y reclamar la devolución de la seña.\n- Una vez entregado el trabajo tiene Garantia de 24hs para chequeo y posibles reclamos, luego de ese tiempo se considera como SATISFACTORIO y no tiene derecho a réplica.')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de presupuesto',
                'verbose_name_plural': 'Configuración de presupuesto',
            },
        ),
    ]
