# Generated by Django 5.2.1 on 2026-08-27 23:02

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracionpresupuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=120)),
                ('grupo', models.CharField(blank=True, help_text="Agrupador para lectura, ej: 'Ocupación', 'Sueldos', 'Impuestos', 'Servicios'.", max_length=60)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('periodicidad', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual'), ('unico', 'Único / amortizable')], default='mensual', max_length=10)),
                ('meses_amortizacion', models.PositiveIntegerField(default=12, help_text="Solo aplica si la periodicidad es 'Único'. En cuántos meses se reparte.")),
                ('activo', models.BooleanField(default=True)),
                ('vigencia_desde', models.DateField(default=django.utils.timezone.localdate)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Costo fijo',
                'verbose_name_plural': 'Costos fijos',
                'ordering': ('grupo', 'concepto'),
            },
        ),
        migrations.CreateModel(
            name='ParametrosProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operarios', models.PositiveIntegerField(default=1, help_text='Personas que producen (no incluye administración).')),
                ('horas_dia', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('dias_mes', models.PositiveIntegerField(default=22)),
                ('ratio_productivas', models.DecimalField(decimal_places=3, default=Decimal('0.700'), help_text='Proporción de las horas disponibles que se dedican efectivamente a producir (el resto es atención, compras, limpieza, tiempo muerto). Entre 0 y 1. Ajustar cada trimestre con datos reales.', max_digits=4)),
                ('factor_correccion_tiempos', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplicador global sobre los tiempos estimados de cada producto. Arranca en 1,00. Si el total de horas vendidas del mes es sistemáticamente menor a las horas realmente trabajadas, subirlo.', max_digits=5)),
                ('vigencia_desde', models.DateField(default=django.utils.timezone.localdate)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parámetros de producción',
                'verbose_name_plural': 'Parámetros de producción',
            },
        ),
    ]
