# Generated by Django 5.2.1 on 2026-08-28 01:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_costofijo_parametrosproduccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosproduccion',
            name='margen_objetivo',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.30'), help_text="Margen del método nuevo sobre el costo total (material a costo + estructura). Es distinto del 'factor' del producto (que es markup sobre el material). Ej: 1,30 = 30% sobre el costo total.", max_digits=4),
        ),
    ]
