# Generated by Django 5.2.1 on 2026-08-29 16:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_parametrosproduccion_margen_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosproduccion',
            name='horas_legacy',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Horas fijas que usa el MÉTODO VIEJO (el que se cobra) para la mano de obra: cobrado = material×factor + horas_legacy×costo_hora + empaquetado. Congela el precio cobrado para que sembrar los tiempos de producción (que alimentan el método nuevo) no lo mueva. Andamio temporal: se retira cuando se pase a cobrar el precio nuevo.', max_digits=5),
        ),
    ]
