# Generated by Django 5.2.1 on 2026-08-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_feriado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costofijo',
            name='periodicidad',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('cuatrimestral', 'Cuatrimestral'), ('anual', 'Anual'), ('unico', 'Único / amortizable')], default='mensual', max_length=15),
        ),
    ]
