# Generated by Django 5.0.6 on 2024-06-30 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('producto', models.TextField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('senia', models.FloatField(blank=True, null=True)),
                ('saldo', models.FloatField(blank=True, null=True)),
                ('estado', models.TextField(choices=[('Sin seña', 'Sin seña'), ('Señado', 'Señado'), ('En proceso', 'En proceso'), ('Para retirar', 'Para retirar'), ('Entregado', 'Entregado'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='Sin seña', max_length=100)),
                ('presupuesto', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('encargado', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
