# Generated by Django 5.2.1 on 2025-08-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='bloqueado_cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
