# Generated by Django 5.2.1 on 2025-08-23 21:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_bloqueado_cancelado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViajeCadete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('origen', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Viaje de cadete',
                'verbose_name_plural': 'Viajes de cadete',
                'ordering': ['-fecha'],
            },
        ),
    ]
