# Generated by Django 5.2.1 on 2026-01-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_viajecadete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.TextField(choices=[('No iniciado', 'No iniciado'), ('En proceso', 'En proceso'), ('Terminado (falta pago)', 'Terminado (falta pago)'), ('Terminado y pagado', 'Terminado y pagado')], default='Sin seña', max_length=100),
        ),
    ]
