# Generated by Django 5.2.1 on 2026-04-09 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_negocio'),
        ('pedidos', '0005_pedido_fecha_entrega'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='encargado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.TextField(choices=[('No iniciado', 'No iniciado'), ('En proceso', 'En proceso'), ('Terminado (falta pago)', 'Terminado (falta pago)'), ('Terminado y pagado', 'Terminado y pagado')], default='No iniciado', max_length=100),
        ),
    ]
