# Generated by Django 5.2.1 on 2026-10-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedido_cliente_alter_pedido_encargado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.TextField(choices=[('No iniciado', 'No iniciado'), ('En proceso', 'En proceso'), ('Terminado (falta pago)', 'Terminado (falta pago)'), ('Terminado y pagado', 'Terminado y pagado'), ('Cancelado', 'Cancelado')], default='No iniciado', max_length=100),
        ),
    ]
