# Generated by Django 5.2.1 on 2026-08-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedido_cliente_alter_pedido_encargado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
