# Generated by Django 5.2.1 on 2026-10-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_pedido_estado'),
        ('pedidos', '0007_alter_pedido_updated'),
    ]

    operations = [
    ]
