# Generated by Django 5.2.1 on 2026-07-29 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0006_alter_pedido_cliente_alter_pedido_encargado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.CharField(choices=[('homologacion', 'Homologación'), ('produccion', 'Producción')], max_length=20)),
                ('tipo_cbte', models.IntegerField(choices=[(11, 'Factura C'), (12, 'Nota de Débito C'), (13, 'Nota de Crédito C')], default=11)),
                ('punto_venta', models.IntegerField()),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('concepto', models.IntegerField(choices=[(1, 'Productos'), (2, 'Servicios'), (3, 'Productos y Servicios')], default=1)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('doc_tipo', models.IntegerField(choices=[(80, 'CUIT'), (86, 'CUIL'), (96, 'DNI'), (99, 'Consumidor Final')], default=99)),
                ('doc_nro', models.BigIntegerField(default=0)),
                ('cond_iva_receptor', models.IntegerField(blank=True, null=True)),
                ('receptor_nombre', models.CharField(blank=True, max_length=200)),
                ('cae', models.CharField(blank=True, max_length=20)),
                ('cae_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('autorizado', 'Autorizado'), ('error', 'Error'), ('anulado', 'Anulado')], default='borrador', max_length=20)),
                ('respuesta_afip', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comprobante_asociado', models.ForeignKey(blank=True, help_text='Factura original referenciada por una nota de crédito/débito.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='facturacion.comprobante')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='TokenAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.CharField(choices=[('homologacion', 'Homologación'), ('produccion', 'Producción')], max_length=20)),
                ('servicio', models.CharField(default='wsfe', max_length=20)),
                ('token', models.TextField()),
                ('sign', models.TextField()),
                ('generado', models.DateTimeField(auto_now=True)),
                ('expiracion', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Token de acceso ARCA',
                'verbose_name_plural': 'Tokens de acceso ARCA',
                'unique_together': {('ambiente', 'servicio')},
            },
        ),
    ]
