# Generated by Django 5.2.1 on 2026-09-05 16:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMonotributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K')], help_text='Letra de la categoría de monotributo vigente (A a K).', max_length=1)),
                ('tope_anual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tope de ingresos brutos anuales de la categoría, según la tabla vigente de ARCA.', max_digits=15)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de monotributo',
                'verbose_name_plural': 'Configuración de monotributo',
            },
        ),
    ]
