# Generated by Django 5.2.1 on 2026-01-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleSugerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, unique=True)),
                ('frecuencia', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
