# Generated by Django 5.2.1 on 2026-04-09 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_metodo_contacto'),
        ('presupuestos', '0002_detallesugerido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='cliente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
    ]
