# Generated by Django 5.2.1 on 2026-08-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0003_alter_presupuesto_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
