# Generated by Django 5.0.6 on 2024-06-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='factor',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
