# Generated by Django 5.0.6 on 2024-07-19 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='caso_part',
            new_name='empaquetado',
        ),
    ]
