# Generated by Django 5.0.6 on 2024-07-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_rename_caso_part_producto_empaquetado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='t_produccion',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
