# Generated by Django 5.0.6 on 2024-07-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_t_produccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
