# Generated by Django 5.0.6 on 2024-07-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_producto_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cant_area',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
