# Generated by Django 5.2.1 on 2025-07-27 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0001_initial'),
        ('productos', '0009_categoria_id_alter_categoria_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('unidad_composicion', models.CharField(default='unidad', max_length=20)),
                ('factor_conversion', models.PositiveIntegerField(default=1)),
                ('ancho', models.FloatField(blank=True, default=0, null=True)),
                ('alto', models.FloatField(blank=True, default=0, null=True)),
                ('stock', models.FloatField(default=0)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='alto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ancho',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cant_area',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='created',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='desc_plata',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='desc_porcentaje',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='empaquetado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='info_adic',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='presupuesto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='t_produccion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tercerizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='factor',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ComponenteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(help_text='Cantidad en unidad de composición, ej: hojas')),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('alternativo', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.insumo')),
            ],
            options={
                'unique_together': {('producto', 'insumo')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='insumos',
            field=models.ManyToManyField(related_name='productos', through='productos.ComponenteProducto', to='productos.insumo'),
        ),
        migrations.CreateModel(
            name='ProductoCotizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=1)),
                ('desc_plata', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('desc_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('t_produccion', models.IntegerField(default=0)),
                ('empaquetado', models.BooleanField(default=False)),
                ('resultado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cliente', models.CharField(blank=True, max_length=200, null=True)),
                ('info_adic', models.TextField(blank=True, null=True)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.presupuesto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
