# Generated by Django 5.2.1 on 2025-07-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_insumo_remove_producto_alto_remove_producto_ancho_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='alto',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='ancho',
        ),
        migrations.AddField(
            model_name='producto',
            name='alto',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='ancho',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
