# Generated by Django 5.2.1 on 2025-07-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_remove_insumo_alto_remove_insumo_ancho_producto_alto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumo',
            old_name='precio_unitario',
            new_name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
