# Generated by Django 5.2.1 on 2025-07-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_rename_precio_unitario_insumo_precio_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_proveedor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
