# Generated by Django 5.2.1 on 2025-08-11 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0001_initial'),
        ('productos', '0013_producto_precio_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocotizado',
            name='presupuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='presupuestos.presupuesto'),
        ),
    ]
