# Generated by Django 5.2.1 on 2025-08-22 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('productos', '0014_alter_productocotizado_presupuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaltanteInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_faltante', models.FloatField()),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.insumo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
            ],
        ),
    ]
