# Generated by Django 5.2.1 on 2025-08-22 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('productos', '0015_faltanteinsumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faltanteinsumo',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido'),
        ),
    ]
