# Generated by Django 5.2.1 on 2025-08-23 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_alter_faltanteinsumo_pedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='modificado_por',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insumo',
            name='ultima_modificacion',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
