# Generated by Django 5.2.1 on 2026-01-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_insumo_modificado_por_insumo_ultima_modificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productocotizado',
            old_name='producto',
            new_name='insumo',
        ),
        migrations.AddField(
            model_name='productocotizado',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productocotizado',
            name='producto_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
