# Generated by Django 5.2.1 on 2026-06-26 23:02

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_rename_producto_productocotizado_insumo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='insumo',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='uniq_insumo_nombre_ci'),
        ),
    ]
