# Generated by Django 5.2.1 on 2026-08-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_insumo_uniq_insumo_nombre_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productocotizado',
            name='t_produccion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
