# Generated by Django 5.2.1 on 2026-09-21 12:50

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_insumo_uniq_insumo_nombre_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='faltanteinsumo',
            name='motivo_cierre',
            field=models.CharField(blank=True, choices=[('stock', 'Cubierto con stock'), ('pedido', 'Pedido terminado')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('telefono_whatsapp', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('web', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='uniq_proveedor_nombre_ci')],
            },
        ),
        migrations.AddField(
            model_name='insumo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos', to='productos.proveedor'),
        ),
    ]
