# Generated by Django 5.2.1 on 2026-08-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0020_alter_categoria_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocotizado',
            name='costo_empaquetado_snap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productocotizado',
            name='costo_insumos_snap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productocotizado',
            name='margen_snap',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AddField(
            model_name='productocotizado',
            name='piso_absoluto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productocotizado',
            name='piso_absorcion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productocotizado',
            name='precio_hora_legacy_snap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productocotizado',
            name='precio_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productocotizado',
            name='precio_sugerido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productocotizado',
            name='tasa_hora_snap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
