# Generated by Django 5.2.1 on 2026-09-21 13:00

from django.db import migrations

ESTADOS_FINALES = ('Terminado (falta pago)', 'Terminado y pagado')


def cerrar(apps, schema_editor):
    """Los pedidos que ya estaban terminados no deben seguir alertando faltantes.
    Se cierran como 'pedido' para que se reactiven si el pedido vuelve a abrirse."""
    FaltanteInsumo = apps.get_model('productos', 'FaltanteInsumo')
    FaltanteInsumo.objects.filter(
        resuelto=False, pedido__estado__in=ESTADOS_FINALES,
    ).update(resuelto=True, motivo_cierre='pedido')


def reabrir(apps, schema_editor):
    FaltanteInsumo = apps.get_model('productos', 'FaltanteInsumo')
    FaltanteInsumo.objects.filter(motivo_cierre='pedido').update(
        resuelto=False, motivo_cierre='')


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0020_proveedor_faltantes'),
        ('pedidos', '0006_alter_pedido_cliente_alter_pedido_encargado_and_more'),
    ]

    operations = [
        migrations.RunPython(cerrar, reabrir),
    ]
