# Generated by Django 5.2.1 on 2026-08-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0021_productocotizado_costo_empaquetado_snap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tiempo_setup',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Horas de preparación por trabajo, independientes de la cantidad (armar el archivo, calibrar, arranque, primera prueba).', max_digits=6),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiempo_unitario',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Horas por unidad producida. La unidad es la misma que la del precio del producto: por hoja (tipo A), por m² (tipo B), por metro lineal (tipo C) o por unidad (tipo D).', max_digits=8),
        ),
    ]
