# Generated by Django 5.2.1 on 2026-09-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0021_cerrar_faltantes_pedidos_terminados'),
        ('productos', '0022_producto_tiempo_setup_producto_tiempo_unitario'),
    ]

    operations = [
    ]
