# Generated by Django 5.2.1 on 2026-01-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_cuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='frecuencia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
