# Generated by Django 5.2.1 on 2026-01-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_frecuencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='negocio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
