# Generated by Django 5.2.1 on 2026-04-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_negocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
