# Generated by Django 5.2.1 on 2026-04-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='metodo_contacto',
            field=models.IntegerField(choices=[(0, 'Visita local'), (1, 'Whatsapp'), (2, 'Instagram'), (3, 'Facebook'), (4, 'Ticktok'), (5, 'Otro')], default=0),
        ),
    ]
