# Generated by Django 5.2.1 on 2026-08-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_metodo_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='condicion_iva',
            field=models.IntegerField(blank=True, choices=[(5, 'Consumidor Final'), (1, 'IVA Responsable Inscripto'), (6, 'Responsable Monotributo'), (4, 'IVA Sujeto Exento'), (13, 'Monotributista Social'), (7, 'Sujeto No Categorizado')], default=None, null=True),
        ),
    ]
