# Generated by Django 5.2.1 on 2026-08-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_condicion_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuit',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
