"""
Django settings for Cotizador project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from django.urls import reverse_lazy
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Inicio la librería environ
env = environ.Env()
environ.Env.read_env()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = tuple(env.list('ALLOWED_HOSTS', default=[]))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'clientes',
    'productos',
    'presupuestos',
    'pedidos',
    'dashboard',
    'facturacion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'productos.middleware.FaltantesMiddleware',
]

ROOT_URLCONF = 'Cotizador.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.rol_usuario',
            ],
            "builtins": ["django.templatetags.l10n"],
        },
    },
]

WSGI_APPLICATION = 'Cotizador.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / env.str('DATABASE_NAME'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_L10N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = True

FORMAT_MODULE_PATH = [
    "Cotizador.formats",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
}

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'


LOGIN_URL = reverse_lazy('login')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'presupuestos/inicio'

# Configuración para el envío de mails
EMAIL_BACKEND = env.str('EMAIL_BACKEND')
EMAIL_HOST = env.str('EMAIL_HOST')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS')
EMAIL_PORT = env.int('EMAIL_PORT')
EMAIL_HOST_USER = env.str('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env.str('EMAIL_HOST_PASSWORD')

# Configuración para el manejo de sesiones.
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = 'sessionid'

if DEBUG:
    IMG_BASE_PATH = str(env.str("IMG_BASE_PATH_DEV"))
    CSS_PATH = str(env.str("CSS_PATH_DEV"))
else:
    IMG_BASE_PATH = str(env.str("IMG_BASE_PATH_PROD"))
    CSS_PATH = str(env.str("CSS_PATH_PROD"))


# ---------------------------------------------------------------------------
# Facturación electrónica ARCA (ex-AFIP)
# ---------------------------------------------------------------------------
# AFIP_ENV controla contra qué ambiente de ARCA se opera. Es INTENCIONALMENTE
# independiente de DEBUG y de la rama git: se puede correr la rama en el server
# real emitiendo contra homologación (CAE de prueba, sin efecto fiscal) y recién
# pasar a 'produccion' cuando esté validado.
AFIP_ENV = env.str("AFIP_ENV", default="homologacion")  # homologacion | produccion
# El certificado y la clave viven en keys/<ambiente>/ (carpeta gitignoreada). El
# path se deriva de BASE_DIR para que el código sea idéntico en dev y producción,
# y el flag AFIP_ENV cambia URLs y certificados a la vez. Se puede override por
# .env (AFIP_CERT_PATH / AFIP_KEY_PATH) si en algún entorno viven en otro lado.
_afip_keys_dir = BASE_DIR / "keys" / AFIP_ENV
AFIP = {
    "ENV": AFIP_ENV,
    "CUIT": env.int("AFIP_CUIT", default=0),
    "PUNTO_VENTA": env.int("AFIP_PUNTO_VENTA", default=1),
    "CERT_PATH": env.str("AFIP_CERT_PATH", default=str(_afip_keys_dir / "certificado.crt")),
    "KEY_PATH": env.str("AFIP_KEY_PATH", default=str(_afip_keys_dir / "clave.key")),
}

# Datos fiscales del EMISOR para el PDF del comprobante. No vienen de la DB (son
# fijos del contribuyente) y son obligatorios legalmente en la factura, así que se
# configuran por .env. Los defaults son PLACEHOLDERS: completá los reales en el
# .env de cada entorno ANTES de emitir en producción.
AFIP_EMISOR = {
    "RAZON_SOCIAL": env.str("AFIP_RAZON_SOCIAL", default="Abraham Risso Fernanda Yamila"),
    "NOMBRE_FANTASIA": env.str("AFIP_NOMBRE_FANTASIA", default="EasyPrint"),
    "DOMICILIO": env.str("AFIP_DOMICILIO", default="(completar domicilio comercial)"),
    "CONDICION_IVA": env.str("AFIP_CONDICION_IVA", default="Responsable Monotributo"),
    "INGRESOS_BRUTOS": env.str("AFIP_INGRESOS_BRUTOS", default="(completar)"),
    "INICIO_ACTIVIDADES": env.str("AFIP_INICIO_ACTIVIDADES", default="(completar)"),
}

# URLs por ambiente. Se resuelven en la capa de servicio según AFIP["ENV"].
AFIP_URLS = {
    "homologacion": {
        "wsaa": "https://wsaahomo.afip.gov.ar/ws/services/LoginCms",
        "wsfev1": "https://wswhomo.afip.gov.ar/wsfev1/service.asmx",
    },
    "produccion": {
        "wsaa": "https://wsaa.afip.gov.ar/ws/services/LoginCms",
        "wsfev1": "https://servicios1.afip.gov.ar/wsfev1/service.asmx",
    },
}
