# Generated by Django 5.2.1 on 2026-10-02 13:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0007_alter_pedido_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('referencia', models.CharField(blank=True, max_length=200)),
                ('tipo', models.CharField(choices=[('senia', 'Seña'), ('pago', 'Pago'), ('devolucion', 'Devolución')], max_length=20)),
                ('medio', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('sin_especificar', 'Sin especificar')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='pedidos.pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
                'ordering': ('-fecha', '-registrado_en', '-id'),
            },
        ),
    ]
